using Blackbird.Applications.Sdk.Common.Dictionaries;

namespace Apps.Crowdin.DataSourceHandlers.EnumHandlers;

public class TypeDataSource : IStaticDataSourceHandler
{
    public Dictionary<string, string> GetData()
    {
        return new()
        {
            {"auto", "auto"},
            {"android", "android"},
            {"macosx", "macosx"},
            {"resx", "resx"},
            {"properties", "properties"},
            {"gettext", "gettext"},
            {"yaml", "yaml"},
            {"php", "php"},
            {"json", "json"},
            {"xml", "xml"},
            {"ini", "ini"},
            {"rc", "rc"},
            {"resw", "resw"},
            {"resjson", "resjson"},
            {"qtts", "qtts"},
            {"joomla", "joomla"},
            {"chrome", "chrome"},
            {"dtd", "dtd"},
            {"dklang", "dklang"},
            {"flex", "flex"},
            {"nsh", "nsh"},
            {"wxl", "wxl"},
            {"xliff", "xliff"},
            {"xliff_two", "xliff_two"},
            {"html", "html"},
            {"haml", "haml"},
            {"txt", "txt"},
            {"csv", "csv"},
            {"md", "md"},
            {"mdx_v1", "mdx_v1"},
            {"mdx_v2", "mdx_v2"},
            {"flsnp", "flsnp"},
            {"fm_html", "fm_html"},
            {"fm_md", "fm_md"},
            {"mediawiki", "mediawiki"},
            {"docx", "docx"},
            {"xlsx", "xlsx"},
            {"sbv", "sbv"},
            {"properties_play", "properties_play"},
            {"properties_xml", "properties_xml"},
            {"maxthon", "maxthon"},
            {"go_json", "go_json"},
            {"dita", "dita"},
            {"idml", "idml"},
            {"mif", "mif"},
            {"stringsdict", "stringsdict"},
            {"plist", "plist"},
            {"vtt", "vtt"},
            {"vdf", "vdf"},
            {"srt", "srt"},
            {"stf", "stf"},
            {"toml", "toml"},
            {"contentful_rt", "contentful_rt"},
            {"svg", "svg"},
            {"js", "js"},
            {"coffee", "coffee"},
            {"ts", "ts"},
            {"i18next_json ", "i18next_json"},
            {"xaml", "xaml"},
            {"arb", "arb"},
            {"adoc", "adoc"},
            {"fbt", "fbt"},
            {"webxml", "webxml"},
            {"nestjs_i18n", "nestjs_i18n"}
        };
    }
}